### ISSUE TITLE
[QUESTION] how to run from sublime text

### ISSUE THREAD

**Issue by lewislepton** [deathbeam/yae#24]
hello,

just one last question before i now really embark on NON. but can NON build from within sublime, or i should say - can it run the code from sublime to NON.

and if so, how

many many thanks

**Comment by albatros2ko** [comment]
I haven't tested it yet but in Sublime Text, you can define your own build settings.

**Comment by lewislepton** [comment]
aye, true. ill have a look see. may just have to do a hodge-podge of my love2d one
i have one for love. which is this

```
{
    "selector": "source.lua",
    "cmd": ["/Applications/Developer/love.app/Contents/MacOS/love", "${project_path:${file_path}}"],
    "file_regex": "^Error: (?:[^:]+: )?([^: ]+?):(\\d+):() ([^:]*)$"
}
```

**Comment by lewislepton** [comment]
to save starting a new thread. i am having trouble even running a .lua file. just trying to run the example from here: https://github.com/non2d/non.examples

and have made my way in the terminal to the asset folder then typed in `non start desktop` it went through many things, then popped up with an error. i did install JDK on my computer before doing all this. the JDK was jdk7u79-macosx-x64.dmg

here is my output from terminal
thanks if you can help

```
lepton:assets lepton$ non start desktop
Starting your application
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle/1.1.3/gradle-1.1.3.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.0.0/robovm-gradle-plugin-1.0.0.pom
Download https://repo1.maven.org/maven2/com/jakewharton/sdkmanager/gradle-plugin/0.12.0/gradle-plugin-0.12.0.pom
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.14/snakeyaml-1.14.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle-core/1.1.3/gradle-core-1.1.3.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-dist-compiler/1.0.0/robovm-dist-compiler-1.0.0.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-dist-parent/1.0.0/robovm-dist-parent-1.0.0.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-parent/1.0.0/robovm-parent-1.0.0.pom
Download https://repo1.maven.org/maven2/org/rauschig/jarchivelib/0.6.0/jarchivelib-0.6.0.pom
Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/25/commons-parent-25.pom
Download https://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8/commons-compress-1.8.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/33/commons-parent-33.pom
Download https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom
Download https://repo1.maven.org/maven2/org/tukaani/xz/1.5/xz-1.5.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/builder/1.1.3/builder-1.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint/24.1.3/lint-24.1.3.pom
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-gradle/5.1/proguard-gradle-5.1.pom
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-parent/5.1/proguard-parent-5.1.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-model/1.1.3/builder-model-1.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-test-api/1.1.3/builder-test-api-1.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/sdklib/24.1.3/sdklib-24.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/sdk-common/24.1.3/sdk-common-24.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/common/24.1.3/common-24.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/manifest-merger/24.1.3/manifest-merger-24.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/ddms/ddmlib/24.1.3/ddmlib-24.1.3.pom
Download https://repo1.maven.org/maven2/com/squareup/javawriter/2.5.0/javawriter-2.5.0.pom
Download https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.pom
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom
Download https://repo1.maven.org/maven2/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-checks/24.1.3/lint-checks-24.1.3.pom
Download https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/4.4/ecj-4.4.pom
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-base/5.1/proguard-base-5.1.pom
Download https://repo1.maven.org/maven2/com/android/tools/annotations/24.1.3/annotations-24.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/layoutlib/layoutlib-api/24.1.3/layoutlib-api-24.1.3.pom
Download https://repo1.maven.org/maven2/com/android/tools/dvlib/24.1.3/dvlib-24.1.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/project/4.1.1/project-4.1.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1.pom
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/17.0/guava-parent-17.0.pom
Download https://repo1.maven.org/maven2/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.pom
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-api/24.1.3/lint-api-24.1.3.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.1/httpcomponents-core-4.1.pom
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
Download https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
Download https://repo1.maven.org/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.pom
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle/1.1.3/gradle-1.1.3.jar
Download https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.0.0/robovm-gradle-plugin-1.0.0.jar
Download https://repo1.maven.org/maven2/com/jakewharton/sdkmanager/gradle-plugin/0.12.0/gradle-plugin-0.12.0.jar
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/gradle-core/1.1.3/gradle-core-1.1.3.jar
Download https://repo1.maven.org/maven2/org/robovm/robovm-dist-compiler/1.0.0/robovm-dist-compiler-1.0.0.jar
Download https://repo1.maven.org/maven2/org/rauschig/jarchivelib/0.6.0/jarchivelib-0.6.0.jar
Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder/1.1.3/builder-1.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint/24.1.3/lint-24.1.3.jar
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-gradle/5.1/proguard-gradle-5.1.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-model/1.1.3/builder-model-1.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-test-api/1.1.3/builder-test-api-1.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/sdklib/24.1.3/sdklib-24.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/sdk-common/24.1.3/sdk-common-24.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/common/24.1.3/common-24.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/manifest-merger/24.1.3/manifest-merger-24.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/ddms/ddmlib/24.1.3/ddmlib-24.1.3.jar
Download https://repo1.maven.org/maven2/com/squareup/javawriter/2.5.0/javawriter-2.5.0.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-checks/24.1.3/lint-checks-24.1.3.jar
Download https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/4.4/ecj-4.4.jar
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-base/5.1/proguard-base-5.1.jar
Download https://repo1.maven.org/maven2/com/android/tools/annotations/24.1.3/annotations-24.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/layoutlib/layoutlib-api/24.1.3/layoutlib-api-24.1.3.jar
Download https://repo1.maven.org/maven2/com/android/tools/dvlib/24.1.3/dvlib-24.1.3.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1.jar
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0.jar
Download https://repo1.maven.org/maven2/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-api/24.1.3/lint-api-24.1.3.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
Download https://repo1.maven.org/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
Android SDK not found. Downloading...
SDK extracted at '/Users/lepton/.android-sdk'. Writing to local.properties.
Build tools 21.1.2 missing. Downloading...
Platform tools missing. Downloading...
Compilation API android-20 missing. Downloading...
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-android/1.5.5/gdx-backend-android-1.5.5.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-android/1.5.5/gdx-backend-android-1.5.5.jar
:resolveDependencies
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.build/0.7.1.201405082137/org.jacoco.build-0.7.1.201405082137.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137.jar
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.ant/0.7.1.201405082137/org.jacoco.ant-0.7.1.201405082137.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/0.7.1.201405082137/org.jacoco.core-0.7.1.201405082137.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.report/0.7.1.201405082137/org.jacoco.report-0.7.1.201405082137.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.ant/0.7.1.201405082137/org.jacoco.ant-0.7.1.201405082137.jar
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/0.7.1.201405082137/org.jacoco.core-0.7.1.201405082137.jar
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.report/0.7.1.201405082137/org.jacoco.report-0.7.1.201405082137.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.5.5/gdx-platform-1.5.5.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.5.5/gdx-box2d-platform-1.5.5.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-freetype-platform/1.5.5/gdx-freetype-platform-1.5.5.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.5.5/gdx-platform-1.5.5-natives-armeabi.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.5.5/gdx-platform-1.5.5-natives-armeabi-v7a.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.5.5/gdx-platform-1.5.5-natives-x86.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.5.5/gdx-box2d-platform-1.5.5-natives-armeabi.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.5.5/gdx-box2d-platform-1.5.5-natives-armeabi-v7a.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.5.5/gdx-box2d-platform-1.5.5-natives-x86.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-freetype-platform/1.5.5/gdx-freetype-platform-1.5.5-natives-armeabi.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-freetype-platform/1.5.5/gdx-freetype-platform-1.5.5-natives-armeabi-v7a.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-freetype-platform/1.5.5/gdx-freetype-platform-1.5.5-natives-x86.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-lwjgl/1.5.5/gdx-backend-lwjgl-1.5.5.pom
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl/2.9.2/lwjgl-2.9.2.pom
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/parent/2.9.2/parent-2.9.2.pom
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl_util/2.9.2/lwjgl_util-2.9.2.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/jlayer/jlayer/1.0.1-gdx/jlayer-1.0.1-gdx.pom
Download https://repo1.maven.org/maven2/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.pom
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2.pom
Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.pom
Download https://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0.pom
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-lwjgl/1.5.5/gdx-backend-lwjgl-1.5.5.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.5.5/gdx-platform-1.5.5-natives-desktop.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.5.5/gdx-box2d-platform-1.5.5-natives-desktop.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-freetype-platform/1.5.5/gdx-freetype-platform-1.5.5-natives-desktop.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl/2.9.2/lwjgl-2.9.2.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl_util/2.9.2/lwjgl_util-2.9.2.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/jlayer/jlayer/1.0.1-gdx/jlayer-1.0.1-gdx.jar
Download https://repo1.maven.org/maven2/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-windows.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-linux.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-osx.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Download https://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
Download https://repo1.maven.org/maven2/org/robovm/robovm-rt/1.0.0/robovm-rt-1.0.0.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-cocoatouch/1.0.0/robovm-cocoatouch-1.0.0.pom
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-robovm/1.5.5/gdx-backend-robovm-1.5.5.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-objc/1.0.0/robovm-objc-1.0.0.pom
Download https://repo1.maven.org/maven2/org/robovm/robovm-rt/1.0.0/robovm-rt-1.0.0.jar
Download https://repo1.maven.org/maven2/org/robovm/robovm-cocoatouch/1.0.0/robovm-cocoatouch-1.0.0.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-robovm/1.5.5/gdx-backend-robovm-1.5.5.jar
Download https://repo1.maven.org/maven2/org/robovm/robovm-objc/1.0.0/robovm-objc-1.0.0.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.5.5/gdx-platform-1.5.5-natives-ios.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.5.5/gdx-box2d-platform-1.5.5-natives-ios.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-freetype-platform/1.5.5/gdx-freetype-platform-1.5.5-natives-ios.jar
:updateAssets UP-TO-DATE
:update UP-TO-DATE
:updateDesktop
:desktop:compileJava
:desktop:processResources UP-TO-DATE
:desktop:classes
:desktop:runException in thread "main" java.io.FileNotFoundException: non/config.yml (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.<init>(FileInputStream.java:146)
at non.desktop.DesktopLauncher.main(DesktopLauncher.java:34)
.  
Task finished with non-zero result

BUILD FAILED
Total time: 4 seconds
```

**Comment by lewislepton** [comment]
ah my mistake. i hdd to actually select the shooter folder rather than the asset folder, within the shooter one. makes sense when i think about it now

**Comment by deathbeam** [comment]
Not skilled with Sublime build system, but I think simly using "cd" to project directory and then executing "non start" should work

``` json
{
    "selector": "source.lua",
    "cmd": ["non", "start"],
    "working_dir": "${project_path:${folder}}"
}
```

Above is assuming that you opened project as folder where `config.yml` resides, and not opened project from `assets` directory.

And you must always navigate your command line to folder where `config.yml` resides, not to assets folder when trying to build or start your project.
